# Generated by Django 3.2.7 on 2021-12-01 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLabel', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user_training_record', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'choice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(db_column='fileName', max_length=512, unique=True)),
                ('imageUrl', models.CharField(db_column='imageUrl', max_length=512, unique=True)),
                ('label', models.BooleanField()),
                ('is_trainSet', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(related_name='choices_made', through='API.Choice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_table',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.imagetable'),
        ),
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
