# Generated by Django 3.2.7 on 2021-11-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
