# Generated by Django 3.2.7 on 2021-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('imagename', models.CharField(db_column='ImageName', max_length=512, primary_key=True, serialize=False)),
                ('imageurl', models.CharField(db_column='ImageUrl', max_length=512, unique=True)),
                ('label', models.IntegerField()),
            ],
            options={
                'db_table': 'image_table',
                'managed': False,
            },
        ),
    ]
