# Generated by Django 3.2.7 on 2021-10-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_cornbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetable',
            options={'managed': True},
        ),
    ]
