# Generated by Django 3.2.7 on 2021-10-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_cornbot', '0002_alter_imagetable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetable',
            options={'managed': False},
        ),
    ]
